/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 home.gltf --transform
Author: cybergaukler (https://sketchfab.com/craylon)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/vrkspace-tag-smarthome-77b50892dcf34a5396b4e5329bdd43f3
Title: VRKSpace-Tag: Smarthome
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/home-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Home_0.geometry}
          material={materials.HomeMaterial}
        />
        <mesh
          geometry={nodes.Home_1.geometry}
          material={materials.RoofMaterial}
        />
        <mesh
          geometry={nodes.Smart_0.geometry}
          material={materials.BulbMaterial}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/home-transformed.glb");
