/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 optima.gltf --transfor
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/optima-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.imagetostl_mesh0.geometry}
        material={materials.mat0}
      />
      <mesh
        geometry={nodes.imagetostl_mesh1.geometry}
        material={materials.mat1}
      />
    </group>
  );
}

useGLTF.preload("/optima-transformed.glb");
